version: '3.9'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  python:
    depends_on:
      - database
    build: .